{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6415ed3a-7e83-4752-bf4c-27deccbc70d7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x1e4d66c1bd0>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# ============================================================\n",
    "# NORTHFIELD & CO.\n",
    "# BUSINESS PERFORMANCE DASHBOARD \n",
    "# ============================================================\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "from dash import Dash, dcc, html, Input, Output\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 1. LOAD DATA\n",
    "# ============================================================\n",
    "\n",
    "FILE_PATH = \"C:\\\\Users\\\\Aleena\\\\Downloads\\\\Northfield_Co_Case_Study.xlsx\"\n",
    "SHEET_NAME = \"Master data\"\n",
    "\n",
    "df = pd.read_excel(FILE_PATH, sheet_name=SHEET_NAME)\n",
    "df[\"Date\"] = pd.to_datetime(df[\"Date\"])\n",
    "df[\"Year\"] = df[\"Date\"].dt.year\n",
    "df[\"Year_Month\"] = df[\"Date\"].dt.to_period(\"M\").astype(str)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 2. CREATE TOTAL PAID MEDIA\n",
    "# ============================================================\n",
    "\n",
    "# spend_Google and spend_Meta are already roll-ups.\n",
    "other_media = [\n",
    "    \"influencer_spend\",\n",
    "    \"Awin_spend\",\n",
    "    \"microsoft_spend\",\n",
    "    \"criteo_spend\",\n",
    "    \"cost_outbrain\"\n",
    "]\n",
    "\n",
    "df[\"Total_Paid_Media\"] = (\n",
    "    df[\"spend_Google\"]\n",
    "    + df[\"spend_Meta\"]\n",
    "    + df[other_media].sum(axis=1)\n",
    ")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 3. DASH APP\n",
    "# ============================================================\n",
    "\n",
    "app = Dash(__name__)\n",
    "app.title = \"Northfield & Co. | Business Dashboard\"\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 4. STYLES\n",
    "# ============================================================\n",
    "\n",
    "PAGE = {\n",
    "    \"fontFamily\": \"Arial, sans-serif\",\n",
    "    \"backgroundColor\": \"#F3F6FA\",\n",
    "    \"minHeight\": \"100vh\",\n",
    "    \"padding\": \"24px 34px\"\n",
    "}\n",
    "\n",
    "HEADER = {\n",
    "    \"background\": \"linear-gradient(135deg, #111827, #374151)\",\n",
    "    \"color\": \"white\",\n",
    "    \"padding\": \"28px 32px\",\n",
    "    \"borderRadius\": \"16px\",\n",
    "    \"marginBottom\": \"18px\",\n",
    "    \"boxShadow\": \"0 4px 14px rgba(0,0,0,0.10)\"\n",
    "}\n",
    "\n",
    "PANEL = {\n",
    "    \"backgroundColor\": \"white\",\n",
    "    \"padding\": \"12px\",\n",
    "    \"borderRadius\": \"14px\",\n",
    "    \"boxShadow\": \"0 2px 10px rgba(0,0,0,0.07)\",\n",
    "    \"marginBottom\": \"18px\"\n",
    "}\n",
    "\n",
    "FILTER_PANEL = {\n",
    "    \"backgroundColor\": \"white\",\n",
    "    \"padding\": \"20px\",\n",
    "    \"borderRadius\": \"14px\",\n",
    "    \"boxShadow\": \"0 2px 10px rgba(0,0,0,0.07)\",\n",
    "    \"marginBottom\": \"18px\"\n",
    "}\n",
    "\n",
    "CARD = {\n",
    "    \"backgroundColor\": \"white\",\n",
    "    \"padding\": \"18px 16px\",\n",
    "    \"borderRadius\": \"14px\",\n",
    "    \"boxShadow\": \"0 2px 10px rgba(0,0,0,0.07)\",\n",
    "    \"textAlign\": \"center\",\n",
    "    \"flex\": \"1\",\n",
    "    \"minWidth\": \"175px\"\n",
    "}\n",
    "\n",
    "CARD_TITLE = {\n",
    "    \"fontSize\": \"12px\",\n",
    "    \"fontWeight\": \"700\",\n",
    "    \"letterSpacing\": \"0.5px\",\n",
    "    \"color\": \"#6B7280\",\n",
    "    \"marginBottom\": \"8px\"\n",
    "}\n",
    "\n",
    "CARD_VALUE = {\n",
    "    \"fontSize\": \"25px\",\n",
    "    \"fontWeight\": \"700\",\n",
    "    \"color\": \"#111827\"\n",
    "}\n",
    "\n",
    "SECTION_TITLE = {\n",
    "    \"fontSize\": \"18px\",\n",
    "    \"fontWeight\": \"700\",\n",
    "    \"color\": \"#111827\",\n",
    "    \"margin\": \"4px 4px 10px 4px\"\n",
    "}\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 5. HELPER FUNCTIONS\n",
    "# ============================================================\n",
    "\n",
    "def money(value):\n",
    "    if pd.isna(value):\n",
    "        return \"$0\"\n",
    "    return f\"${value:,.0f}\"\n",
    "\n",
    "\n",
    "def pct(value):\n",
    "    if pd.isna(value):\n",
    "        return \"0.0%\"\n",
    "    return f\"{value:.1f}%\"\n",
    "\n",
    "\n",
    "def comparison(grouped, label_col, value_col, name_a, name_b):\n",
    "    \"\"\"Return means for two binary groups, safely.\"\"\"\n",
    "    a = grouped.loc[grouped[label_col] == 1, value_col]\n",
    "    b = grouped.loc[grouped[label_col] == 0, value_col]\n",
    "    return (\n",
    "        a.iloc[0] if len(a) else np.nan,\n",
    "        b.iloc[0] if len(b) else np.nan\n",
    "    )\n",
    "\n",
    "\n",
    "def make_card(title, value):\n",
    "    return [\n",
    "        html.Div(title, style=CARD_TITLE),\n",
    "        html.Div(value, style=CARD_VALUE)\n",
    "    ]\n",
    "\n",
    "\n",
    "def base_layout(fig, title, height=390):\n",
    "    fig.update_layout(\n",
    "        title={\"text\": title, \"x\": 0.02, \"xanchor\": \"left\"},\n",
    "        template=\"plotly_white\",\n",
    "        height=height,\n",
    "        margin={\"l\": 55, \"r\": 25, \"t\": 55, \"b\": 55},\n",
    "        font={\"family\": \"Arial, sans-serif\", \"color\": \"#374151\"},\n",
    "        hoverlabel={\"bgcolor\": \"white\"}\n",
    "    )\n",
    "    return fig\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 6. LAYOUT\n",
    "# ============================================================\n",
    "\n",
    "years = sorted(df[\"Year\"].unique())\n",
    "\n",
    "app.layout = html.Div(\n",
    "    style=PAGE,\n",
    "    children=[\n",
    "\n",
    "        # Header\n",
    "        html.Div(\n",
    "            style=HEADER,\n",
    "            children=[\n",
    "                html.H1(\n",
    "                    \"Northfield & Co.\",\n",
    "                    style={\"margin\": \"0\", \"fontSize\": \"32px\"}\n",
    "                ),\n",
    "                html.Div(\n",
    "                    \"Business Performance Dashboard\",\n",
    "                    style={\n",
    "                        \"fontSize\": \"20px\",\n",
    "                        \"marginTop\": \"5px\",\n",
    "                        \"color\": \"#E5E7EB\"\n",
    "                    }\n",
    "                ),\n",
    "                html.P(\n",
    "                    \"Revenue performance, customer acquisition, promotions, media and seasonal patterns\",\n",
    "                    style={\n",
    "                        \"margin\": \"10px 0 0 0\",\n",
    "                        \"color\": \"#D1D5DB\"\n",
    "                    }\n",
    "                )\n",
    "            ]\n",
    "        ),\n",
    "\n",
    "        # Filters\n",
    "        html.Div(\n",
    "            style=FILTER_PANEL,\n",
    "            children=[\n",
    "                html.Div(\"FILTERS\", style={\n",
    "                    \"fontSize\": \"13px\",\n",
    "                    \"fontWeight\": \"700\",\n",
    "                    \"color\": \"#6B7280\",\n",
    "                    \"marginBottom\": \"12px\"\n",
    "                }),\n",
    "                html.Div(\n",
    "                    style={\n",
    "                        \"display\": \"flex\",\n",
    "                        \"gap\": \"18px\",\n",
    "                        \"flexWrap\": \"wrap\"\n",
    "                    },\n",
    "                    children=[\n",
    "                        html.Div(\n",
    "                            style={\"flex\": \"1\", \"minWidth\": \"210px\"},\n",
    "                            children=[\n",
    "                                html.Label(\"Year\", style={\"fontWeight\": \"600\"}),\n",
    "                                dcc.Dropdown(\n",
    "                                    id=\"year-filter\",\n",
    "                                    options=[{\"label\": \"All Years\", \"value\": \"All\"}] + [\n",
    "                                        {\"label\": str(y), \"value\": int(y)} for y in years\n",
    "                                    ],\n",
    "                                    value=\"All\",\n",
    "                                    clearable=False\n",
    "                                )\n",
    "                            ]\n",
    "                        ),\n",
    "                        html.Div(\n",
    "                            style={\"flex\": \"1\", \"minWidth\": \"210px\"},\n",
    "                            children=[\n",
    "                                html.Label(\"Promotion\", style={\"fontWeight\": \"600\"}),\n",
    "                                dcc.Dropdown(\n",
    "                                    id=\"promotion-filter\",\n",
    "                                    options=[\n",
    "                                        {\"label\": \"All\", \"value\": \"All\"},\n",
    "                                        {\"label\": \"Promotion\", \"value\": \"Promotion\"},\n",
    "                                        {\"label\": \"No Promotion\", \"value\": \"No Promotion\"}\n",
    "                                    ],\n",
    "                                    value=\"All\",\n",
    "                                    clearable=False\n",
    "                                )\n",
    "                            ]\n",
    "                        ),\n",
    "                        html.Div(\n",
    "                            style={\"flex\": \"1\", \"minWidth\": \"210px\"},\n",
    "                            children=[\n",
    "                                html.Label(\"UWG Mailing\", style={\"fontWeight\": \"600\"}),\n",
    "                                dcc.Dropdown(\n",
    "                                    id=\"mailing-filter\",\n",
    "                                    options=[\n",
    "                                        {\"label\": \"All\", \"value\": \"All\"},\n",
    "                                        {\"label\": \"UWG Mailing\", \"value\": \"UWG Mailing\"},\n",
    "                                        {\"label\": \"No Mailing\", \"value\": \"No Mailing\"}\n",
    "                                    ],\n",
    "                                    value=\"All\",\n",
    "                                    clearable=False\n",
    "                                )\n",
    "                            ]\n",
    "                        )\n",
    "                    ]\n",
    "                )\n",
    "            ]\n",
    "        ),\n",
    "\n",
    "        # KPI cards\n",
    "        html.Div(\n",
    "            style={\n",
    "                \"display\": \"flex\",\n",
    "                \"gap\": \"16px\",\n",
    "                \"flexWrap\": \"wrap\",\n",
    "                \"marginBottom\": \"18px\"\n",
    "            },\n",
    "            children=[\n",
    "                html.Div(id=\"kpi-total-revenue\", style=CARD),\n",
    "                html.Div(id=\"kpi-new-customer\", style=CARD),\n",
    "                html.Div(id=\"kpi-average-revenue\", style=CARD),\n",
    "                html.Div(id=\"kpi-paid-media\", style=CARD),\n",
    "                html.Div(id=\"kpi-media-share\", style=CARD)\n",
    "            ]\n",
    "        ),\n",
    "\n",
    "        # Daily revenue - full width\n",
    "        html.Div(\n",
    "            style=PANEL,\n",
    "            children=[dcc.Graph(id=\"daily-revenue-chart\")]\n",
    "        ),\n",
    "\n",
    "        # Monthly + media\n",
    "        html.Div(\n",
    "            style={\n",
    "                \"display\": \"grid\",\n",
    "                \"gridTemplateColumns\": \"repeat(auto-fit, minmax(420px, 1fr))\",\n",
    "                \"gap\": \"18px\"\n",
    "            },\n",
    "            children=[\n",
    "                html.Div(style=PANEL, children=[dcc.Graph(id=\"monthly-revenue-chart\")]),\n",
    "                html.Div(style=PANEL, children=[dcc.Graph(id=\"media-chart\")])\n",
    "            ]\n",
    "        ),\n",
    "\n",
    "        # Promotions + mailing\n",
    "        html.Div(\n",
    "            style={\n",
    "                \"display\": \"grid\",\n",
    "                \"gridTemplateColumns\": \"repeat(auto-fit, minmax(420px, 1fr))\",\n",
    "                \"gap\": \"18px\"\n",
    "            },\n",
    "            children=[\n",
    "                html.Div(style=PANEL, children=[dcc.Graph(id=\"promotion-chart\")]),\n",
    "                html.Div(style=PANEL, children=[dcc.Graph(id=\"mailing-chart\")])\n",
    "            ]\n",
    "        ),\n",
    "\n",
    "        # BFCM + holiday\n",
    "        html.Div(\n",
    "            style={\n",
    "                \"display\": \"grid\",\n",
    "                \"gridTemplateColumns\": \"repeat(auto-fit, minmax(420px, 1fr))\",\n",
    "                \"gap\": \"18px\"\n",
    "            },\n",
    "            children=[\n",
    "                html.Div(style=PANEL, children=[dcc.Graph(id=\"bfcm-chart\")]),\n",
    "                html.Div(style=PANEL, children=[dcc.Graph(id=\"holiday-chart\")])\n",
    "            ]\n",
    "        ),\n",
    "\n",
    "        # New customer + media relationship\n",
    "        html.Div(\n",
    "            style={\n",
    "                \"display\": \"grid\",\n",
    "                \"gridTemplateColumns\": \"repeat(auto-fit, minmax(420px, 1fr))\",\n",
    "                \"gap\": \"18px\"\n",
    "            },\n",
    "            children=[\n",
    "                html.Div(style=PANEL, children=[dcc.Graph(id=\"new-customer-chart\")]),\n",
    "                html.Div(style=PANEL, children=[dcc.Graph(id=\"scatter-chart\")])\n",
    "            ]\n",
    "        ),\n",
    "\n",
    "        # Key findings and recommendations\n",
    "        html.Div(\n",
    "            style={\n",
    "                \"display\": \"grid\",\n",
    "                \"gridTemplateColumns\": \"repeat(auto-fit, minmax(420px, 1fr))\",\n",
    "                \"gap\": \"18px\"\n",
    "            },\n",
    "            children=[\n",
    "                html.Div(\n",
    "                    style={\n",
    "                        **PANEL,\n",
    "                        \"padding\": \"22px 25px\"\n",
    "                    },\n",
    "                    children=[\n",
    "                        html.H3(\"Key Findings\", style=SECTION_TITLE),\n",
    "                        html.Div(id=\"key-findings\")\n",
    "                    ]\n",
    "                ),\n",
    "                html.Div(\n",
    "                    style={\n",
    "                        **PANEL,\n",
    "                        \"padding\": \"22px 25px\"\n",
    "                    },\n",
    "                    children=[\n",
    "                        html.H3(\"Business Recommendations\", style=SECTION_TITLE),\n",
    "                        html.Div(id=\"recommendations\")\n",
    "                    ]\n",
    "                )\n",
    "            ]\n",
    "        ),\n",
    "\n",
    "        # Interpretation note\n",
    "        html.Div(\n",
    "            style={\n",
    "                \"backgroundColor\": \"#EEF2F7\",\n",
    "                \"padding\": \"16px 22px\",\n",
    "                \"borderRadius\": \"12px\",\n",
    "                \"color\": \"#4B5563\",\n",
    "                \"fontSize\": \"13px\",\n",
    "                \"marginTop\": \"2px\"\n",
    "            },\n",
    "            children=[\n",
    "                html.Strong(\"Important: \"),\n",
    "                \"Promotion, mailing, BFCM, holiday and paid-media comparisons show observed associations. \",\n",
    "                \"They do not by themselves establish that these factors caused changes in revenue.\"\n",
    "            ]\n",
    "        )\n",
    "    ]\n",
    ")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 7. CALLBACK\n",
    "# ============================================================\n",
    "\n",
    "@app.callback(\n",
    "    [\n",
    "        Output(\"kpi-total-revenue\", \"children\"),\n",
    "        Output(\"kpi-new-customer\", \"children\"),\n",
    "        Output(\"kpi-average-revenue\", \"children\"),\n",
    "        Output(\"kpi-paid-media\", \"children\"),\n",
    "        Output(\"kpi-media-share\", \"children\"),\n",
    "        Output(\"daily-revenue-chart\", \"figure\"),\n",
    "        Output(\"monthly-revenue-chart\", \"figure\"),\n",
    "        Output(\"media-chart\", \"figure\"),\n",
    "        Output(\"promotion-chart\", \"figure\"),\n",
    "        Output(\"mailing-chart\", \"figure\"),\n",
    "        Output(\"bfcm-chart\", \"figure\"),\n",
    "        Output(\"holiday-chart\", \"figure\"),\n",
    "        Output(\"new-customer-chart\", \"figure\"),\n",
    "        Output(\"scatter-chart\", \"figure\"),\n",
    "        Output(\"key-findings\", \"children\"),\n",
    "        Output(\"recommendations\", \"children\")\n",
    "    ],\n",
    "    [\n",
    "        Input(\"year-filter\", \"value\"),\n",
    "        Input(\"promotion-filter\", \"value\"),\n",
    "        Input(\"mailing-filter\", \"value\")\n",
    "    ]\n",
    ")\n",
    "def update_dashboard(selected_year, selected_promotion, selected_mailing):\n",
    "\n",
    "    filtered = df.copy()\n",
    "\n",
    "    if selected_year != \"All\":\n",
    "        filtered = filtered[filtered[\"Year\"] == int(selected_year)]\n",
    "\n",
    "    if selected_promotion == \"Promotion\":\n",
    "        filtered = filtered[filtered[\"Promotion_Discount\"] == 1]\n",
    "    elif selected_promotion == \"No Promotion\":\n",
    "        filtered = filtered[filtered[\"Promotion_Discount\"] == 0]\n",
    "\n",
    "    if selected_mailing == \"UWG Mailing\":\n",
    "        filtered = filtered[filtered[\"UWG_Mailing\"] == 1]\n",
    "    elif selected_mailing == \"No Mailing\":\n",
    "        filtered = filtered[filtered[\"UWG_Mailing\"] == 0]\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # Empty result\n",
    "    # --------------------------------------------------------\n",
    "    if filtered.empty:\n",
    "        empty_fig = go.Figure()\n",
    "        empty_fig.update_layout(\n",
    "            template=\"plotly_white\",\n",
    "            title=\"No data available for the selected filters\",\n",
    "            xaxis={\"visible\": False},\n",
    "            yaxis={\"visible\": False}\n",
    "        )\n",
    "        empty_card = make_card(\"NO DATA\", \"—\")\n",
    "        empty_text = [html.P(\"No observations match the selected filters.\")]\n",
    "        return (\n",
    "            empty_card, empty_card, empty_card, empty_card, empty_card,\n",
    "            empty_fig, empty_fig, empty_fig, empty_fig, empty_fig,\n",
    "            empty_fig, empty_fig, empty_fig, empty_fig,\n",
    "            empty_text, empty_text\n",
    "        )\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # KPIs\n",
    "    # --------------------------------------------------------\n",
    "    total_revenue = filtered[\"Total_Revenue\"].sum()\n",
    "    new_customer_revenue = filtered[\"Revenue_New_Customer\"].sum()\n",
    "    average_daily_revenue = filtered[\"Total_Revenue\"].mean()\n",
    "    total_paid_media = filtered[\"Total_Paid_Media\"].sum()\n",
    "    media_share = total_paid_media / total_revenue * 100 if total_revenue else 0\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # Aggregations\n",
    "    # --------------------------------------------------------\n",
    "    daily = filtered.sort_values(\"Date\")\n",
    "\n",
    "    monthly = (\n",
    "        filtered.groupby(\"Year_Month\", as_index=False)\n",
    "        .agg(\n",
    "            Total_Revenue=(\"Total_Revenue\", \"sum\"),\n",
    "            New_Customer_Revenue=(\"Revenue_New_Customer\", \"sum\")\n",
    "        )\n",
    "        .sort_values(\"Year_Month\")\n",
    "    )\n",
    "\n",
    "    media_data = pd.DataFrame({\n",
    "        \"Channel\": [\"Google\", \"Meta\", \"Other Media\"],\n",
    "        \"Spend\": [\n",
    "            filtered[\"spend_Google\"].sum(),\n",
    "            filtered[\"spend_Meta\"].sum(),\n",
    "            filtered[other_media].sum().sum()\n",
    "        ]\n",
    "    })\n",
    "\n",
    "    def binary_average(column):\n",
    "        result = (\n",
    "            filtered.groupby(column, as_index=False)[\"Total_Revenue\"]\n",
    "            .mean()\n",
    "            .rename(columns={\"Total_Revenue\": \"Average_Revenue\"})\n",
    "        )\n",
    "        return result\n",
    "\n",
    "    promotion_data = binary_average(\"Promotion_Discount\")\n",
    "    promotion_data[\"Label\"] = promotion_data[\"Promotion_Discount\"].map({\n",
    "        0: \"No Promotion\",\n",
    "        1: \"Promotion\"\n",
    "    })\n",
    "\n",
    "    mailing_data = binary_average(\"UWG_Mailing\")\n",
    "    mailing_data[\"Label\"] = mailing_data[\"UWG_Mailing\"].map({\n",
    "        0: \"No Mailing\",\n",
    "        1: \"UWG Mailing\"\n",
    "    })\n",
    "\n",
    "    bfcm_data = binary_average(\"BFCM_Promo_Effect\")\n",
    "    bfcm_data[\"Label\"] = bfcm_data[\"BFCM_Promo_Effect\"].map({\n",
    "        0: \"Non-BFCM\",\n",
    "        1: \"BFCM\"\n",
    "    })\n",
    "\n",
    "    holiday_data = binary_average(\"holiday_list\")\n",
    "    holiday_data[\"Label\"] = holiday_data[\"holiday_list\"].map({\n",
    "        0: \"Non-Holiday\",\n",
    "        1: \"Holiday\"\n",
    "    })\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 1. Daily revenue\n",
    "    # --------------------------------------------------------\n",
    "    daily_fig = go.Figure()\n",
    "    daily_fig.add_trace(go.Scatter(\n",
    "        x=daily[\"Date\"],\n",
    "        y=daily[\"Total_Revenue\"],\n",
    "        mode=\"lines\",\n",
    "        name=\"Daily Revenue\",\n",
    "        line={\"width\": 1.8},\n",
    "        hovertemplate=(\n",
    "            \"<b>%{x|%d %b %Y}</b><br>\"\n",
    "            \"Revenue: $%{y:,.0f}<extra></extra>\"\n",
    "        )\n",
    "    ))\n",
    "    daily_fig = base_layout(daily_fig, \"Daily Total Revenue Over Time\", 470)\n",
    "    daily_fig.update_layout(hovermode=\"x unified\")\n",
    "    daily_fig.update_xaxes(title=\"Date\")\n",
    "    daily_fig.update_yaxes(title=\"Revenue ($)\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 2. Monthly revenue\n",
    "    # --------------------------------------------------------\n",
    "    monthly_fig = go.Figure()\n",
    "    monthly_fig.add_trace(go.Scatter(\n",
    "        x=monthly[\"Year_Month\"],\n",
    "        y=monthly[\"Total_Revenue\"],\n",
    "        mode=\"lines+markers\",\n",
    "        name=\"Revenue\",\n",
    "        hovertemplate=(\n",
    "            \"<b>%{x}</b><br>Revenue: $%{y:,.0f}<extra></extra>\"\n",
    "        )\n",
    "    ))\n",
    "    monthly_fig = base_layout(monthly_fig, \"Monthly Revenue Trend\")\n",
    "    monthly_fig.update_xaxes(title=\"Month\", tickangle=-45)\n",
    "    monthly_fig.update_yaxes(title=\"Revenue ($)\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 3. Media\n",
    "    # --------------------------------------------------------\n",
    "    media_fig = go.Figure()\n",
    "    media_fig.add_trace(go.Bar(\n",
    "        x=media_data[\"Channel\"],\n",
    "        y=media_data[\"Spend\"],\n",
    "        text=[money(x) for x in media_data[\"Spend\"]],\n",
    "        textposition=\"auto\",\n",
    "        hovertemplate=(\n",
    "            \"<b>%{x}</b><br>Spend: $%{y:,.0f}<extra></extra>\"\n",
    "        )\n",
    "    ))\n",
    "    media_fig = base_layout(media_fig, \"Paid Media Spend by Channel\")\n",
    "    media_fig.update_xaxes(title=\"Channel\")\n",
    "    media_fig.update_yaxes(title=\"Spend ($)\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 4. Promotion\n",
    "    # --------------------------------------------------------\n",
    "    promotion_fig = go.Figure()\n",
    "    promotion_fig.add_trace(go.Bar(\n",
    "        x=promotion_data[\"Label\"],\n",
    "        y=promotion_data[\"Average_Revenue\"],\n",
    "        text=[money(x) for x in promotion_data[\"Average_Revenue\"]],\n",
    "        textposition=\"auto\",\n",
    "        hovertemplate=(\n",
    "            \"<b>%{x}</b><br>Average Daily Revenue: $%{y:,.0f}<extra></extra>\"\n",
    "        )\n",
    "    ))\n",
    "    promotion_fig = base_layout(\n",
    "        promotion_fig,\n",
    "        \"Average Daily Revenue: Promotion vs No Promotion\"\n",
    "    )\n",
    "    promotion_fig.update_xaxes(title=\"Promotion Status\")\n",
    "    promotion_fig.update_yaxes(title=\"Average Revenue ($)\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 5. Mailing\n",
    "    # --------------------------------------------------------\n",
    "    mailing_fig = go.Figure()\n",
    "    mailing_fig.add_trace(go.Bar(\n",
    "        x=mailing_data[\"Label\"],\n",
    "        y=mailing_data[\"Average_Revenue\"],\n",
    "        text=[money(x) for x in mailing_data[\"Average_Revenue\"]],\n",
    "        textposition=\"auto\",\n",
    "        hovertemplate=(\n",
    "            \"<b>%{x}</b><br>Average Daily Revenue: $%{y:,.0f}<extra></extra>\"\n",
    "        )\n",
    "    ))\n",
    "    mailing_fig = base_layout(\n",
    "        mailing_fig,\n",
    "        \"Average Daily Revenue: UWG Mailing vs No Mailing\"\n",
    "    )\n",
    "    mailing_fig.update_xaxes(title=\"Mailing Status\")\n",
    "    mailing_fig.update_yaxes(title=\"Average Revenue ($)\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 6. BFCM\n",
    "    # --------------------------------------------------------\n",
    "    bfcm_fig = go.Figure()\n",
    "    bfcm_fig.add_trace(go.Bar(\n",
    "        x=bfcm_data[\"Label\"],\n",
    "        y=bfcm_data[\"Average_Revenue\"],\n",
    "        text=[money(x) for x in bfcm_data[\"Average_Revenue\"]],\n",
    "        textposition=\"auto\",\n",
    "        hovertemplate=(\n",
    "            \"<b>%{x}</b><br>Average Daily Revenue: $%{y:,.0f}<extra></extra>\"\n",
    "        )\n",
    "    ))\n",
    "    bfcm_fig = base_layout(\n",
    "        bfcm_fig,\n",
    "        \"Average Daily Revenue: BFCM vs Non-BFCM\"\n",
    "    )\n",
    "    bfcm_fig.update_xaxes(title=\"BFCM Status\")\n",
    "    bfcm_fig.update_yaxes(title=\"Average Revenue ($)\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 7. Holiday\n",
    "    # --------------------------------------------------------\n",
    "    holiday_fig = go.Figure()\n",
    "    holiday_fig.add_trace(go.Bar(\n",
    "        x=holiday_data[\"Label\"],\n",
    "        y=holiday_data[\"Average_Revenue\"],\n",
    "        text=[money(x) for x in holiday_data[\"Average_Revenue\"]],\n",
    "        textposition=\"auto\",\n",
    "        hovertemplate=(\n",
    "            \"<b>%{x}</b><br>Average Daily Revenue: $%{y:,.0f}<extra></extra>\"\n",
    "        )\n",
    "    ))\n",
    "    holiday_fig = base_layout(\n",
    "        holiday_fig,\n",
    "        \"Average Daily Revenue: Holiday vs Non-Holiday\"\n",
    "    )\n",
    "    holiday_fig.update_xaxes(title=\"Holiday Status\")\n",
    "    holiday_fig.update_yaxes(title=\"Average Revenue ($)\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 8. New customer revenue\n",
    "    # --------------------------------------------------------\n",
    "    new_customer_fig = go.Figure()\n",
    "    new_customer_fig.add_trace(go.Scatter(\n",
    "        x=monthly[\"Year_Month\"],\n",
    "        y=monthly[\"New_Customer_Revenue\"],\n",
    "        mode=\"lines+markers\",\n",
    "        name=\"New Customer Revenue\",\n",
    "        hovertemplate=(\n",
    "            \"<b>%{x}</b><br>New-Customer Revenue: $%{y:,.0f}<extra></extra>\"\n",
    "        )\n",
    "    ))\n",
    "    new_customer_fig = base_layout(\n",
    "        new_customer_fig,\n",
    "        \"Monthly New-Customer Revenue\"\n",
    "    )\n",
    "    new_customer_fig.update_xaxes(title=\"Month\", tickangle=-45)\n",
    "    new_customer_fig.update_yaxes(title=\"New-Customer Revenue ($)\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 9. Revenue vs paid media\n",
    "    # --------------------------------------------------------\n",
    "    scatter_fig = go.Figure()\n",
    "    scatter_fig.add_trace(go.Scatter(\n",
    "        x=filtered[\"Total_Paid_Media\"],\n",
    "        y=filtered[\"Total_Revenue\"],\n",
    "        mode=\"markers\",\n",
    "        marker={\"size\": 7, \"opacity\": 0.60},\n",
    "        hovertemplate=(\n",
    "            \"Paid Media: $%{x:,.0f}<br>Revenue: $%{y:,.0f}<extra></extra>\"\n",
    "        )\n",
    "    ))\n",
    "    scatter_fig = base_layout(\n",
    "        scatter_fig,\n",
    "        \"Daily Revenue vs Paid Media Spend\"\n",
    "    )\n",
    "    scatter_fig.update_xaxes(title=\"Total Paid Media Spend ($)\")\n",
    "    scatter_fig.update_yaxes(title=\"Total Revenue ($)\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # KEY FINDINGS - generated from the currently filtered data\n",
    "    # --------------------------------------------------------\n",
    "    findings = []\n",
    "\n",
    "    # Promotion comparison\n",
    "    if len(promotion_data) == 2:\n",
    "        promo_mean = promotion_data.loc[\n",
    "            promotion_data[\"Promotion_Discount\"] == 1,\n",
    "            \"Average_Revenue\"\n",
    "        ].iloc[0]\n",
    "        no_promo_mean = promotion_data.loc[\n",
    "            promotion_data[\"Promotion_Discount\"] == 0,\n",
    "            \"Average_Revenue\"\n",
    "        ].iloc[0]\n",
    "        diff = (promo_mean - no_promo_mean) / no_promo_mean * 100 if no_promo_mean else np.nan\n",
    "        direction = \"higher\" if diff >= 0 else \"lower\"\n",
    "        findings.append(\n",
    "            f\"Average daily revenue on promotion days was {abs(diff):.1f}% {direction} than on non-promotion days.\"\n",
    "        )\n",
    "\n",
    "    # BFCM comparison\n",
    "    if len(bfcm_data) == 2:\n",
    "        bfcm_mean = bfcm_data.loc[\n",
    "            bfcm_data[\"BFCM_Promo_Effect\"] == 1,\n",
    "            \"Average_Revenue\"\n",
    "        ].iloc[0]\n",
    "        non_bfcm_mean = bfcm_data.loc[\n",
    "            bfcm_data[\"BFCM_Promo_Effect\"] == 0,\n",
    "            \"Average_Revenue\"\n",
    "        ].iloc[0]\n",
    "        diff = (bfcm_mean - non_bfcm_mean) / non_bfcm_mean * 100 if non_bfcm_mean else np.nan\n",
    "        direction = \"higher\" if diff >= 0 else \"lower\"\n",
    "        findings.append(\n",
    "            f\"Average daily revenue on BFCM days was {abs(diff):.1f}% {direction} than on non-BFCM days.\"\n",
    "        )\n",
    "\n",
    "    # Holiday comparison\n",
    "    if len(holiday_data) == 2:\n",
    "        holiday_mean = holiday_data.loc[\n",
    "            holiday_data[\"holiday_list\"] == 1,\n",
    "            \"Average_Revenue\"\n",
    "        ].iloc[0]\n",
    "        non_holiday_mean = holiday_data.loc[\n",
    "            holiday_data[\"holiday_list\"] == 0,\n",
    "            \"Average_Revenue\"\n",
    "        ].iloc[0]\n",
    "        diff = (holiday_mean - non_holiday_mean) / non_holiday_mean * 100 if non_holiday_mean else np.nan\n",
    "        direction = \"higher\" if diff >= 0 else \"lower\"\n",
    "        findings.append(\n",
    "            f\"Average daily revenue on holiday days was {abs(diff):.1f}% {direction} than on non-holiday days.\"\n",
    "        )\n",
    "\n",
    "    # Mailing comparison\n",
    "    if len(mailing_data) == 2:\n",
    "        mailing_mean = mailing_data.loc[\n",
    "            mailing_data[\"UWG_Mailing\"] == 1,\n",
    "            \"Average_Revenue\"\n",
    "        ].iloc[0]\n",
    "        no_mailing_mean = mailing_data.loc[\n",
    "            mailing_data[\"UWG_Mailing\"] == 0,\n",
    "            \"Average_Revenue\"\n",
    "        ].iloc[0]\n",
    "        diff = (mailing_mean - no_mailing_mean) / no_mailing_mean * 100 if no_mailing_mean else np.nan\n",
    "        direction = \"higher\" if diff >= 0 else \"lower\"\n",
    "        findings.append(\n",
    "            f\"Average daily revenue on UWG mailing days was {abs(diff):.1f}% {direction} than on non-mailing days.\"\n",
    "        )\n",
    "\n",
    "    # Highest revenue day\n",
    "    peak = filtered.loc[filtered[\"Total_Revenue\"].idxmax()]\n",
    "    findings.append(\n",
    "        f\"The highest observed revenue day was {peak['Date'].strftime('%d %b %Y')}, with revenue of {money(peak['Total_Revenue'])}.\"\n",
    "    )\n",
    "\n",
    "    findings.append(\n",
    "        f\"Paid media represented {media_share:.1f}% of total revenue over the selected period.\"\n",
    "    )\n",
    "\n",
    "    findings_list = [\n",
    "        html.Li(\n",
    "            item,\n",
    "            style={\"marginBottom\": \"10px\", \"lineHeight\": \"1.5\"}\n",
    "        )\n",
    "        for item in findings\n",
    "    ]\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # RECOMMENDATIONS - decision-support, not causal claims\n",
    "    # --------------------------------------------------------\n",
    "    recommendations = [\n",
    "        \"Use BFCM and other high-revenue periods as priority periods for campaign planning, while evaluating incremental revenue and profitability before increasing spend.\",\n",
    "        \"Compare promotion and mailing performance with campaign cost, customer acquisition and margin measures to determine whether observed revenue differences translate into business value.\",\n",
    "        \"Investigate the largest daily revenue spikes individually and cross-check promotions, mailings, holidays and media activity before drawing conclusions about their drivers.\",\n",
    "        \"Use the dashboard filters to examine whether the observed patterns are consistent across years rather than relying only on the overall period average.\"\n",
    "    ]\n",
    "\n",
    "    recommendations_list = [\n",
    "        html.Li(\n",
    "            item,\n",
    "            style={\"marginBottom\": \"10px\", \"lineHeight\": \"1.5\"}\n",
    "        )\n",
    "        for item in recommendations\n",
    "    ]\n",
    "\n",
    "    return (\n",
    "        make_card(\"TOTAL REVENUE\", money(total_revenue)),\n",
    "        make_card(\"NEW-CUSTOMER REVENUE\", money(new_customer_revenue)),\n",
    "        make_card(\"AVERAGE DAILY REVENUE\", money(average_daily_revenue)),\n",
    "        make_card(\"TOTAL PAID MEDIA\", money(total_paid_media)),\n",
    "        make_card(\"PAID MEDIA / REVENUE\", pct(media_share)),\n",
    "        daily_fig,\n",
    "        monthly_fig,\n",
    "        media_fig,\n",
    "        promotion_fig,\n",
    "        mailing_fig,\n",
    "        bfcm_fig,\n",
    "        holiday_fig,\n",
    "        new_customer_fig,\n",
    "        scatter_fig,\n",
    "        html.Ul(findings_list, style={\"paddingLeft\": \"22px\", \"marginBottom\": \"0\"}),\n",
    "        html.Ul(recommendations_list, style={\"paddingLeft\": \"22px\", \"marginBottom\": \"0\"})\n",
    "    )\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 8. RUN APPLICATION\n",
    "# ============================================================\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(debug=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "363982be-204b-4795-b10c-15a50f83fbbc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
